# Generated by Django 4.1.5 on 2023-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mojetokeny',
            options={'ordering': ['dolarova_hodnota', 'nazev']},
        ),
        migrations.AlterField(
            model_name='mojetokeny',
            name='dolarova_hodnota',
            field=models.IntegerField(),
        ),
    ]
