# Generated by Django 4.1.5 on 2023-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_mojetokeny_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_tokenu', models.CharField(max_length=16)),
                ('dolar_hodnota', models.IntegerField()),
                ('proc', models.CharField(max_length=16)),
            ],
        ),
    ]
