# Generated by Django 4.1.5 on 2023-02-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_portfolio_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='dolar_hodnota',
            new_name='dolarova_hodnota',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='proc',
            new_name='procenta',
        ),
    ]
