# Generated by Django 4.1.5 on 2023-02-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_rename_dolar_hodnota_portfolio_dolarova_hodnota_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-dolarova_hodnota', 'nazev_tokenu']},
        ),
    ]
