# Generated by Django 4.1.5 on 2023-02-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_portfolio_procenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MojeTokeny',
        ),
    ]
